### ISSUE TITLE
Immediate To-Dos

### ISSUE THREAD

**Issue by jensimmons** [mozilla/css-grid-inspector#12]
This tool is an experiment from the Mozilla Developer Relations Team. We want to release a more 'official' extension. These are the things we want to do now to get us there.

- [x] Change name
- [x] Move repo to Mozilla's account
- [x] Write up README w/ help docs
- [x] Create a tool for turning individual grids on and off, panel that opens
- [x] Ge the tool to save state, and not revert to grid-off every time the page is reloaded
- [ ] Look at the issues labeled 'bug' and see what is going on, see if we can fix them. They are examples where the lines are not where they should be.
- [ ] Create an icon or logo for branding (needed ?)
- [x] Put into Mozilla Add-On Store

**Comment by potch** [comment]
Updated with the new panel UI and the AMO hosting.
